python bench_glue_AIO.py \
    --model_name_or_path gpt2 \
    --run_name gpt2-3epoch \
    --task_name sst2 \
    --save_strategy "epoch" \
    --do_train --logging_strategy no --save_strategy no \
    --do_eval \
    --max_seq_length 128 \
    --per_device_train_batch_size 72 \
    --per_device_eval_batch_size 1 \
    --learning_rate 5e-5 \
    --num_train_epochs 3 \
    --evaluation_strategy 'epoch' \
    --seed 1337 \
    --output_dir ./data/ \
    --overwrite_output_dir